{
  updateConfig: true,
  saveConfigOnExit: true,
  useMqtt: false,
  traceLevel: 0,
  bluetoothDevices: {"A0_E9_DB_10_3F_B9": {onConnectCommand: "echo $DEVICE connected", onDisconnectCommand: null},
                    "other_a2dp_sinks":  {onConnectCommand: "echo $DEVICE connected", onDisconnectCommand: null} },                  
}
